services:
  - type: web
    name: django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jb_backend_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db

databases:
  - name: django-db
    plan: free
